# Generated by Django 3.1.3 on 2020-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201116_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания вопроса'),
        ),
    ]
